#!/usr/bin/env ansible-playbook
---
- name: ansible play example
  hosts: localhost
  tasks:
    - name: run apt install
      become: yes
      apt:
        update_cache: yes
        name:
          - python3-dev
          - python3-pip
